const FETCH_ALL_USERS_ROUTE = 'users';
const FETCH_ALL_ARTICLES_ROUTE = 'articles';
const FETCH_ALL_COMMENTS_ROUTE = 'comments';

const SERVER_REQUEST = {
  FETCH_ALL_USERS_ROUTE,
  FETCH_ALL_ARTICLES_ROUTE,
  FETCH_ALL_COMMENTS_ROUTE,
};

export default SERVER_REQUEST;
